---
- name: kernel_settings
  hosts: all
  become: true
  vars: 
    kernel_settings_sysctl:
    - name: fs.file-max
      value: 400000
    - name: kernel.threads-max
      value: 65536
    kernel_settings_sysfs:
    - name: /sys/class/net/lo/mtu
      value: 65000
    kernel_settings_transparent_hugepages: madvise

  roles: 
    - linux-system-roles.kernel_settings