---
- name: selinux module
  hosts: all
  become: true
  vars: 
    selinux_state: "enforcing"
    selinux_policy: "targeted"
  tasks:
    - name: SElinux plicy and state
      ansible.posix.selinux:
       state: "{{ selinux_state }}"
       policy: "{{ selinux_policy }}"
      notify: relabel and reboot

  handlers:
    - name: relabel and reboot
      ansible.builtin.file:
       path: "/.autorelabel"
       state: touch
      when: 
        - selinux_state != 'disabled'
      listen: relabel and reboot

    - name: reboot 
      ansible.builtin.reboot:
      listen: relabel and reboot