---
- name: postgresql
  hosts: all
  become: true
  vars:
    db_name: testdb
    backup_dir: "/backups"
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    - name: backup directory
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        mode: 0777
        owner: postgres
        state: directory

    - name: backup db
      community.postgresql.postgresql_db:
        state: dump
        name: "{{ db_name }}"
        target: "{{ backup_dir }}/{{ db_name }}.gz"
      become: true
      become_user: postgres