---
- name: install solr
  hosts: solr
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update_cache if needed
      apt: update_cache=true cache_valid=3600
  
  handlers:
    - name: restart solr
      service: name=solr state=restarted

  tasks:
    - name: Install Jave.
      apt: name=openjdk-8-jdk state=present
    - name: Download Solr
      get_url:
        url: https://www.apache.org/dyn/closer.lua/solr/solr/{{solr_version}}/solr-{{solr_version}}-src.tgz?action=download
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version}}/README"

    - name: Run solr installation script
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr

    - name: Ensure solr is started and enabled at boot
      service: name=solr state=started enabled=yes
