---
- name: check if a file exist
  hosts: all
  become: false
  vars: 
    myfile: /home/devops/test.txt
  tasks: 
  - name: check if a file exist
    ansible.builtin.stat:
      path: "{{ myfile }}"
    register: file_data

  - name: report file exist
    ansible.builtin.debug:
      msg: "the file {{ myfile }} exist"
    when: file_data.stat.exists
  - name: report file not exist
    ansible.builtin.debug:
      msg: "The file {{ myfile }}does'nt exist"
    when: not file_data.stat.exists