---
- name: change user password
  hosts: all
  become: true
  vars:
    myuser: "nash"
    mypassword: "password"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512')}}"