---
- name: setup webserver with vhost
  hosts: all
  become: true
  vars:
    app_user: "apache"
    http_host: "example.com"
    http_conf: "example.com.conf"
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: document root exists
      ansible.builtin.file:
        path: "/var/www/{{ http_host}}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0775'
        setype: "httpd_sys_content_t"

    - name: custom index.html
      ansible.builtin.copy:
        dest: "/var/www/{{http_host}}/index.html"
        content: |
         Custom Web Page

    - name: setup Apache virtualhost
      ansible.builtin.template:
        src: "templates/apache.conf.j2"
        dest: "/etc/httpd/conf.d/{{ http_conf }}"

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true